### ISSUE TITLE
Roadmap for the agreements 

### ISSUE THREAD

**Issue by jwalsh** [FirstToDisclose/CodeAcrossBoston#13]
This should cover some of the expectations for recording user acceptance of agreements.

**Comment by dazzaji** [comment]
In addition to working for the agreements, it would be helpful to have a general roadmap.  I've updated this item to be a roadmap, of which agreements are a part.  Note in the attached whiteboard file the basic high level items on the left (Persons, Labels, Documents and Agreements).  These are some basic inputs to core functional areas to focus upon for a roadmap.  Eventually, in Django, each may benefit from an "app" and a "model".  In the short term, they are a handy reference point to understand basic key functional elements and pillars
![designelements](https://cloud.githubusercontent.com/assets/2357755/6596071/08412576-c7c7-11e4-85cb-f5f8be90b021.jpg)
.

**Comment by jwalsh** [comment]
This issue was moved to FirstToDisclose/firsttodisclose.net#18
