### ISSUE TITLE
Meeting with Google

### ISSUE THREAD

**Issue by dah366** [FirstToDisclose/CodeAcrossBoston#17]
We want to set up a meeting with Google to show them what we have done so far and get feedback. Professor Aksin doesn't want to set it up too early in the development process but I don't think we should wait until we have a finished product incase there are features they want us to implement. Please let me know your thoughts on this as well as possible timing for the meeting.

**Comment by jwalsh** [comment]
That sounds good.  I'll be working on the core features / issues this week.

**Comment by dah366** [comment]
Can anyone suggest a timeframe? it doesn't have to be a date, it can be based on the development of the project.

**Comment by jwalsh** [comment]
We're working on Disclosure submission and agreement acceptance today: we should be able to track back from there to a demo date by tomorrow.

**Comment by jwalsh** [comment]
This issue was moved to FirstToDisclose/firsttodisclose.net#15
