### ISSUE TITLE
Collect requirements and constraints for valid date-time stamps

### ISSUE THREAD

**Issue by dazzaji** [FirstToDisclose/CodeAcrossBoston#23]
Some go-getter law student of technical guru is welcome to take this on.  We will need trustworthy digital time stamping as part of the functional capability of this system.  One can derive a set of basic functional requirements and nice to have features from the linked resources collected at the following project wiki page:

https://github.com/FirstToDisclose/CodeAcrossBoston/wiki/Trusted-Time-Stamping

When reviewing the materials linked from the above page, extract only the most relevant factors.  I've whittled down the sources to only a small handful and there are a few things to learn from each perspective (vendors with systems to sell, practice pointers for lawyers, internet standards, etc).  Focus on the practical issues related to entering persuasive evidence at trial and the practical technical and business practice capabilities.

Please add the draft requirements/constraints to the same wiki page with the links (above) and update this ticket once relevant functions, features and other valuable information has been extracted from the content at each link.  When ready, please update this ticket to let people know it is time to review your work and potentially close this ticket when there is a good initial requirements document.  More tickets will be pulled on time stamping and therefore having a wiki page that can grow and improve  will help keep the information learned and history of this thread easy to document and jump into later.

**Comment by jwalsh** [comment]
This issue was moved to FirstToDisclose/firsttodisclose.net#11
