### ISSUE TITLE
Modification breaks concept of agreeing to disclose?

### ISSUE THREAD

**Issue by BWStearns** [FirstToDisclose/CodeAcrossBoston#24]
## Scenario:

Disclosure v0:
- ID: 123
- Title: Free Nuclear Power
- Body: [shows how to make free nuclear power]
- Consented: True

**our discloser realizes he can monetize this and edits the disclosure to hide his secret sauce**

Disclosure v1:
- ID: 123
- Title: Free Breadsticks
- Body: [shows how to make free breadsticks]
- Consented: True

---

Consent was given to disclose the information which seems to be intended as irrevocable, edits without preserving the original, the diffs between versions or some other trail seem to break the concept.

**Comment by jwalsh** [comment]
This issue was moved to FirstToDisclose/firsttodisclose.net#9

**Comment by jwalsh** [comment]
This issue was moved to FirstToDisclose/firsttodisclose.net#10
