### ISSUE TITLE
MIT IDP should be a supported provider

### ISSUE THREAD

**Issue by jwalsh** [FirstToDisclose/CodeAcrossBoston#6]
Login has Google, Twitter, and Facebook but should also have MIT.

**Comment by dazzaji** [comment]
Here is the key documentation site: https://oidc.mit.edu/

I have access via my MIT account to provision the service.  Let's do it!

**Comment by jwalsh** [comment]
This issue was moved to FirstToDisclose/firsttodisclose.net#23
