### ISSUE TITLE
Before disclosure submission CC license is accepted 

### ISSUE THREAD

**Issue by jwalsh** [FirstToDisclose/CodeAcrossBoston#7]

**Comment by jwalsh** [comment]
The acceptance of the site agreement as well as the CC should be a single action.

**Comment by dazzaji** [comment]
The operative language for users to see/accept before submission of content is: 

/start/

"Use Creative Commons Attribution License *
We accept content under licensed for use under Creative Commons Attribution 4.0 International (CC BY 4.0) http://creativecommons.org/licenses/by/4.0"

[CheckBox]  I hereby license the content submitted through this form under Attribution 4.0 International (CC BY 4.0)

/end/

Here is a working example: https://law.mit.edu/GeekHouse

**Comment by dazzaji** [comment]
Here is an implementation of qna markup focused on eliciting tags based on the patent classification taxonomy:

Q(1): Does the innovation you are disclosing apply to "Lighting"?
A: Yes.
    Q(1.1): Does it relate to a Light Source? 
    A: Yes.
        Q(1.1.1):  Great.  Your US Classification Code for that aspect of your innovation is D26/1.   Is it related to an Electric Light Bulb (34)?
        A: Yes.
            Q(1.1.1.1): Great.  Your new US Classification Code for that aspect of your innovation is D26/2.   Is it Fluorescent?
            A: Yes
                Q(1.1.1.1.1): Great. Your new US Classification Code for that aspect of your innovation is D26/3.
            A: No.
                Q(1.1.1.1.2): Is it Simulative?
                A: Yes
                    Q(1.1.1.1.2.1): Great. Your new US Classification Code for that aspect of your innovation is D26/4. Is it simulative of a candle or Flame?
                    A: Yes
                        Q(1.1.1.1.2.1.1): Great. Your new US Classification Code for that aspect of your innovation is D26/5.
                    A: No
                        Q(1.1.1.1.2.1.2): Your US Classification code for this aspect of your innovation is still D26/4.
        A: No
            Q(1.1.1.2): Your US Classification code is still D26/1 for this aspect of your innovation. Does it relate to a candle?
            A: Yes  
                Q(1.1.1.2.1): Great your new US Classification Code is D26/6. Is it Simulative?
                A: Yes
                    Q(1.1.1.2.1.1): Great your new US Classification Code is D26/7.
                A: No
                    Q(1.1.1.2.1.2): Your US Classification code is still D26/6
            A: No
                Q(1.1.1.2.2): Your US Classification code is Still D26/1. Is it a torch?
                A: Yes
                    Q(1.1.1.2.2.1): Great. Your new US Classification Code is D26/8
                A: No
                    Q(1.1.1.2.2.2): Your US Classification code is still D26/1
    A: No.
        Q(1.1.2): Does it relate to a Candle Holder?
        A: Yes.
            Q(1.1.2.1): Great your US Classification code is D26/9.
        A: No
            Q(1.1.2.2): Okay then. GOTO:2
A: No
    Q(1.2): Okay then. GOTO:2
Q(2): Head over to <a href="http://FirstToDisclose.org">FirstToDisclose.org</a> for other options.

**Comment by jwalsh** [comment]
This issue was moved to FirstToDisclose/firsttodisclose.net#22
